In [2]:
import numpy as np

an_array  =  np.array([3,33,333])
print(type(an_array))

<class 'numpy.ndarray'>


In [2]:
an_array.shape

(3,)

In [3]:
print(an_array[0],an_array[1],an_array[2])

3 33 333


In [5]:
an_array[0]=888
print(an_array)

[888  33 333]


### Como crear un numpy array

In [7]:
another = np.array([[11,12,13] , [21,22,23]])
print(another)

print(f'El shape es de 2 filas y 3 columnas {another.shape}')
print(f'Accesando a los elementos [0,0], [0,1], [1,0] del array {another[0,0], another[0,1], another[1,0]}')

[[11 12 13]
 [21 22 23]]
El shape es de 2 filas y 3 columnas (2, 3)
Accesando a los elementos [0,0], [0,1], [1,0] del array (11, 12, 21)


### Mas formas de crear un array

In [16]:
# Array de 2 columnas y 2 filas de puro 0
ex2 = np.zeros((2,2))

# Crea matriz diagonal de 1 de 2x2
ex3 = np.eye(2,2)

# Crea un array de unos
ex4 = np.ones((1,2))

# Crea un array de 2x2 lleno de 1 numero
ex4_1 = np.full((2,2), 9.0) 

# Crea un array con floats entre 0 y 1
ex5 = np.random.random((2,2))

print('Matriz de ceros',ex2,'\n \n Matriz diagonal',ex3,'''
\n \n Matriz de unos''',ex4,'''\n \n Matriz de nueves''',ex4_1,'''
\n \n Matriz random''',ex5)

Matriz de ceros [[0. 0.]
 [0. 0.]] 
 
 Matriz diagonal [[1. 0.]
 [0. 1.]] 

 
 Matriz de unos [[1. 1.]] 
 
 Matriz de nueves [[9. 9.]
 [9. 9.]] 

 
 Matriz random [[0.52198015 0.51077785]
 [0.41516742 0.18659166]]


### Slicing

In [22]:
# Slicing se ubica por filas y luego columnas

an_array2  =  np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(f'''Este es el array \n
{an_array2} \n
y este es el  slicing del array \n
{an_array2[:2,1:3]}''')

Este es el array 

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]] 

y este es el  slicing del array 

[[12 13]
 [22 23]]


In [23]:
# Slicing
a_slice= an_array2[:2,1:3]

print(f'El valor anterior del array es :{an_array2[0,1]}')

# Puedes cambiar el valor de un dato en el array a partir del index del slicing
a_slice[0,0] = 1000
print(f'El nuevo valor del array es :{an_array2[0,1]}')

El valor anterior del array es :12
El nuevo valor del array es :1000


In [25]:
# Aplicando un array al Slicing 
a_slice2= np.array(an_array2[:2,1:3])

print(f'El valor anterior del array es :{an_array2[0,1]}')

# Esto ya es otro array, por lo que no se va a modificar la data
a_slice2[0,0] = 12
print(f'El nuevo valor del array es :{an_array2[0,1]}')

El valor anterior del array es :1000
El nuevo valor del array es :1000


### Slicing y shape

In [26]:
# Es 1 lista, por lo que se guarda como 1 sola columna con varias filas
row_rank1 = an_array2[1,:]
print(row_rank1,row_rank1.shape)

# Cuenta como una matriz, por lo que el shape cambia a filas y columnas
row_rank2 = an_array2[1:2,:]
print(row_rank2,row_rank2.shape)

[21 22 23 24] (4,)
[[21 22 23 24]] (1, 4)


### Crear Slicing por indices

In [30]:
an_array3 = np.array([[11,12,13], [21,22,23], [31,32,33],[41,42,43]])

# Indices de columnas
col_indices = np.array([0,1,2,0])

# Indices de filas
row_indices = np.arange(4)

print(col_indices,row_indices)

[0 1 2 0] [0 1 2 3]


In [28]:
# Zipeamos ambos indices e iteramos en la tupla
for row, col in zip(row_indices,col_indices):
    print(row, ',',col)

0 , 0
1 , 1
2 , 2
3 , 0


In [31]:
# Podemos llamar los valores de una lista de indices
print(f'Estos son los valores de los indices anteriores{an_array3[row_indices,col_indices]}')

Estos son los valores de los indices anteriores[11 22 33 41]


In [37]:
# Vamos a sumar 1000 a cada uno de esos valores en el array original
an_array3[row_indices,col_indices]+=1000

print(f'Nuevo array por indices \n{an_array3}')

Nuevo array por indices 
[[1011   12   13]
 [  21 1022   23]
 [  31   32 1033]
 [1041   42   43]]


### Booleanos

In [55]:
# Puedes filtrar y generar booleanos  
an_array4 = np.array([[11,12], [21,22], [31,32]])
an_array4 > 15


array([[False, False],
       [ True,  True],
       [ True,  True]])

In [58]:
# Podemos usar los booleanos como indices para filtrar datos a traves de true
print(an_array4[an_array4 > 15])

print(an_array4[an_array4 % 2 == 0])

[21 22 31 32]
[12 22 32]


In [57]:
# Varios filtros
an_array4[(an_array4 > 20) & (an_array4 < 30)] 


array([21, 22])

In [59]:
an_array4[an_array4 % 2 == 0] += 100
print(an_array4)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


### Tipos de datos

In [60]:
ex6 = np.array([11,12])
print(ex6.dtype)

ex7 = np.array([11.0,12.0])
print(ex7.dtype)

int32
float64


In [61]:
# Puedes agregar el tipo de objeto con int64
ex6 = np.array([11,12], dtype=np.int64)
print(ex6.dtype)

# float64
ex6 = np.array([11,12], dtype=np.float64)
print(ex6.dtype)


int64
float64


### Operaciones

In [63]:
x = np.array([[111,112],[121,122]], dtype=np.int64)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)


In [65]:
# Suma
print(x+y, '\n\n', np.add(x,y))

[[322.1 324.1]
 [342.1 344.1]] 

 [[322.1 324.1]
 [342.1 344.1]]


In [67]:
# Resta
print(x-y, '\n\n', np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]] 

 [[-100.1 -100.1]
 [-100.1 -100.1]]


In [68]:
# Multiplicacion
print(x*y, '\n\n', np.multiply(x,y))

[[23432.1 23755.2]
 [26753.1 27096.2]] 

 [[23432.1 23755.2]
 [26753.1 27096.2]]


In [69]:
# Dividir
print(x/y, '\n\n', np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]] 

 [[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [70]:
# Raiz
print(x**0.5, '\n\n', np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]] 

 [[10.53565375 10.58300524]
 [11.         11.04536102]]


In [72]:
# Exponencial
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


### Metodos estadisticos

In [3]:
arr = 10* np.random.randn(2,5)
arr

array([[ -8.31642904,  -8.58611366, -20.5592389 ,  -7.33620276,
          9.17933937],
       [ -1.87160844, -18.42088467,   1.48122418,  -1.10258919,
          7.95737741]])

In [6]:
# promedio
print(arr.mean())

# promedio por fila
print(arr.mean(axis=1))

# promedio por columna
print(arr.mean(axis=0))

-4.757512570607459
[-7.123729   -2.39129614]
[ -5.09401874 -13.50349916  -9.53900736  -4.21939598   8.56835839]


In [8]:
# suma todos los elementos
arr.sum()

-47.575125706074594

In [9]:
# mediana por filas
print(np.median(arr, axis=1))

[-8.31642904 -1.10258919]


### Sorted

In [11]:
unsorted = np.random.randn(10)
unsorted

array([ 0.88801873, -1.63211814,  1.83244941, -2.06280944,  2.43577799,
       -0.05518903,  0.90689346, -0.89420662, -0.51684258, -2.28033645])

In [15]:
# crear una copia del array y sortealo
sorted_arr = np.array(unsorted)
sorted_arr.sort()

print(unsorted, '\n\n', sorted_arr)

[ 0.88801873 -1.63211814  1.83244941 -2.06280944  2.43577799 -0.05518903
  0.90689346 -0.89420662 -0.51684258 -2.28033645] 

 [-2.28033645 -2.06280944 -1.63211814 -0.89420662 -0.51684258 -0.05518903
  0.88801873  0.90689346  1.83244941  2.43577799]


### Unique

In [17]:
# Solo devuelve los valores unicos 
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


### Operaciones con tipos de datos

In [18]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])

In [20]:
# Operacion de interseccion 1D
print(np.intersect1d(s1,s2))

# Operacion de union 1D
print(np.union1d(s1,s2))

# Operacion de exclusion. Elementos del 1er conjunto que no estan en el 2do
print(np.setdiff1d(s1,s2))

# Operacion booleana. True para elementos del 1er conjunto que estan en el 2do
print(np.in1d(s1,s2))

['bulb' 'chair']
['bulb' 'chair' 'desk' 'lamp']
['desk']
[False  True  True]


### Broadcasting

In [27]:
# Matriz 4x3 de ceros
start = np.zeros((4,3))

# Matris 1x3
add_rows = np.array([1,0,2])

# Suma de arreglos
print(start + add_rows)


[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [25]:
# Define un escalar
add_scalar = np.array([1])

# Suma un escalar
print(start + add_scalar)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
# Arreglo 1 fila
add_cols = np.array([[0,1,2,3]])

# Suma de columna
print(start + add_cols.T)


[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


### Speed Test

In [41]:
from numpy import arange
from timeit import Timer

size    = 1000000
timeits = 1000

# create the ndarray with values 0,1,2...,size-1
nd_array = arange(size)
print( type(nd_array) )

# timer expects the operation as a parameter, 
# here we pass nd_array.sum()
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))

<class 'numpy.ndarray'>
Time taken by numpy ndarray: 0.000359 seconds


In [40]:
# Crea una lista en vez de un array
a_list = list(range(size))
print (type(a_list) )

# timer expects the operation as a parameter, here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list:  %f seconds" % 
      (timer_list.timeit(timeits)/timeits))

<class 'list'>
Time taken by list:  0.021096 seconds


### Ejemplo

In [3]:
an_array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(an_array[0:1,0:2],  an_array[:1,:2],  an_array[0,:-2],  an_array[-3,:2])

[[1 2]] [[1 2]] [1 2] [1 2]
